// Claw Desktop - RSA密钥生成 - 服务端RSA密钥对生成
use rsa::{RsaPrivateKey, pkcs8::{EncodePrivateKey, EncodePublicKey}};
use rand::thread_rng;
use std::fs;
use std::path::PathBuf;
use base64::Engine;

/// RSA密钥对生成配置
pub struct KeyPairConfig {
    pub output_dir: PathBuf,
    pub public_key_output: PathBuf,
    pub private_key_output: PathBuf,
    pub key_size: usize,
}

impl Default for KeyPairConfig {
    fn default() -> Self {
        let manifest_dir = std::env::var("CARGO_MANIFEST_DIR")
            .unwrap_or_else(|_| ".".to_string());
        let project_root = PathBuf::from(&manifest_dir).join("../../..");

        Self {
            output_dir: project_root.join("src-tauri/keys"),
            public_key_output: project_root.join("src/ws/publicKey.ts"),
            private_key_output: project_root.join("src-tauri/keys/private.pem"),
            key_size: 2048,
        }
    }
}

/// 生成的密钥对结果 — 包含PEM格式和指纹
#[derive(Debug)]
pub struct GeneratedKeyPair {
    pub private_pem: String,
    pub public_pem: String,
    pub fingerprint: String,
}

/// 生成RSA密钥对 — 根据配置生成私钥、公钥PEM和SHA256指纹
pub fn generate_keypair(config: &KeyPairConfig) -> Result<GeneratedKeyPair, anyhow::Error> {
    let mut rng = thread_rng();

    let private_key = RsaPrivateKey::new(&mut rng, config.key_size)?;

    let private_pem = private_key
        .to_pkcs8_pem(rsa::pkcs8::LineEnding::default())?
        .to_string();

    let public_key = private_key.to_public_key();
    let public_pem = public_key
        .to_public_key_pem(rsa::pkcs8::LineEnding::default())?
        .to_string();

    let der_bytes = public_key.to_public_key_der()?.as_ref().to_vec();
    let digest = ring::digest::digest(
        &ring::digest::SHA256,
        &der_bytes,
    );
    let fingerprint = hex::encode(&digest.as_ref()[..16]);

    Ok(GeneratedKeyPair {
        private_pem,
        public_pem,
        fingerprint,
    })
}

/// 混淆公钥 — 使用XOR变换和Base64编码保护嵌入前端的公钥
pub fn obfuscate_public_key(pem: &str) -> String {
    let encoded = base64::engine::general_purpose::STANDARD.encode(pem.as_bytes());
    let mut obscured = String::new();

    for (i, c) in encoded.chars().enumerate() {
        let key_byte = ((i as u8).wrapping_mul(7).wrapping_add(13)) & 0xFF;
        obscured.push((c as u8 ^ key_byte) as char);
    }

    format!("qck_{}", base64::engine::general_purpose::STANDARD.encode(obscured.as_bytes()))
}

/// 保存密钥对 — 私钥写入PEM文件，公钥混淆后写入TypeScript源文件
pub fn save_keypair(keypair: &GeneratedKeyPair, config: &KeyPairConfig) -> Result<(), anyhow::Error> {
    fs::create_dir_all(&config.output_dir)?;

    fs::write(&config.private_key_output, &keypair.private_pem)?;
    log::info!("[WS:KeyGen] Private key saved to: {:?}", config.private_key_output);

    let obfuscated = obfuscate_public_key(&keypair.public_pem);
    let ts_content = format!(
r#"/**
 * Embedded RSA public key - auto-generated file, do not modify manually!
 * Generated by: cargo run --bin generate_keys (or WS keygen)
 * Updated: {}
 * Fingerprint: {}
 */

const OBFUSCATE_PREFIX = 'qck_'
const EMBEDDED_KEY_DATA = '{}'

export function getEmbeddedPublicKey(): string {{
  const decoded = deobfuscate(EMBEDDED_KEY_DATA)
  if (!decoded || !decoded.includes('-----BEGIN')) {{
    throw new Error('[Security] Embedded public key is corrupted')
  }}
  return decoded
}}

function deobfuscate(obfuscated: string): string | null {{
  if (!obfuscated) return null

  if (obfuscated.startsWith(OBFUSCATE_PREFIX)) {{
    try {{
      const encodedB64 = obfuscated.slice(OBFUSCATE_PREFIX.length)
      const obscuredBin = atob(encodedB64)
      let encoded = ''
      for (let i = 0; i < obscuredBin.length; i++) {{
        const keyByte = ((i * 7 + 13) & 0xFF)
        encoded += String.fromCharCode(obscuredBin.charCodeAt(i) ^ keyByte)
      }}
      return decodeURIComponent(escape(atob(encoded))
    }} {{ return null }}
  }}

  if (obfuscated.includes('-----BEGIN') && obfuscated.includes('PUBLIC KEY')) {{ return obfuscated }}
  return null
}}

export function getEnvPublicKey(): string {{
  const envKey = (import.meta as any).env?.VITE_PUBLIC_KEY
  if (envKey?.includes('-----BEGIN')) return envKey
  return ''
}}

export function getDefaultPublicKey(): string {{
  return getEmbeddedPublicKey() || getEnvPublicKey()
}}
"#,
        chrono::Local::now().format("%Y-%m-%d %H:%M:%S").to_string(),
        keypair.fingerprint,
        obfuscated
    );

    fs::write(&config.public_key_output, ts_content)?;
    log::info!("[WS:KeyGen] Public key (obfuscated) saved to: {:?}", config.public_key_output);

    let gitignore_path = config.output_dir.join(".gitignore");
    if !gitignore_path.exists() {
        fs::write(&gitignore_path, "# Private keys - DO NOT COMMIT\nprivate.pem\n*.key\n")?;
        log::info!("[WS:KeyGen] Created .gitignore for keys directory");
    }

    Ok(())
}

/// 执行密钥生成流程 — 生成RSA密钥对并保存到文件
pub fn run_keygen() -> Result<(), anyhow::Error> {
    let config = KeyPairConfig::default();

    log::info!("[WS:KeyGen] Generating RSA keypair...");
    log::info!("[WS:KeyGen]   Key size: {} bits", config.key_size);
    log::info!("[WS:KeyGen]   Output dir: {:?}", config.output_dir);

    let keypair = generate_keypair(&config)?;

    log::info!("[WS:KeyGen] Key pair generated:");
    log::info!("[WS:KeyGen]   Fingerprint: {}", keypair.fingerprint);
    log::info!("[WS:KeyGen]   Public key (first 40 chars): {}...", claw_types::truncate_str_safe(&keypair.public_pem, 40));

    save_keypair(&keypair, &config)?;

    log::info!("[WS:KeyGen] Done! You can now:");
    log::info!("[WS:KeyGen]   1. Import getEmbeddedPublicKey() in your auth code");
    log::info!("[WS:KeyGen]   2. Remove the /api/auth/public-key endpoint (no longer needed)");
    log::info!("[WS:KeyGen]   3. Commit src/ws/publicKey.ts to version control");

    Ok(())
}
